"""
Polls Google Ads API for the YouTube subscriber user list and automatically
attaches it to the ad group + updates the audience when it appears.

The subscriber list is auto-generated by Google after the YouTube channel link
propagates (usually 2-24h after linking with EU political ads confirmed).

Run once and leave it — it checks every 15 minutes, attaches the list when ready,
and exits.

Usage:
    python3 scripts/attach_subscriber_list.py
"""
import os
import sys
import time
from datetime import datetime

try:
    from dotenv import load_dotenv
    load_dotenv(".env.local")
except ImportError:
    pass

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, ".."))
sys.path.insert(0, os.path.join(HERE, "..", "api"))

from api._lib import google_ads_client
from google.ads.googleads.v24.common.types import audiences as audiences_pb
from google.protobuf import field_mask_pb2

CID = "3152829803"
AG_ID = "196557300716"
AG_RESOURCE = f"customers/{CID}/adGroups/{AG_ID}"
AUDIENCE_ID = "347448305"
AUDIENCE_RESOURCE = f"customers/{CID}/audiences/{AUDIENCE_ID}"
CUSTOM_AUDIENCE_RESOURCE = f"customers/{CID}/customAudiences/977585709"

POLL_INTERVAL_SECONDS = 900  # 15 minutes
SUBSCRIBER_KEYWORDS = ["subscrib", "musical basics", "mb ", "channel"]


def find_subscriber_list(client, ga_service):
    q = "SELECT user_list.id, user_list.name, user_list.type, user_list.size_for_display, user_list.membership_status FROM user_list ORDER BY user_list.size_for_display DESC"
    rows = list(ga_service.search(customer_id=CID, query=q))
    if not rows:
        return None
    # Look for YouTube subscriber list by name
    for r in rows:
        name_lower = r.user_list.name.lower()
        if any(kw in name_lower for kw in SUBSCRIBER_KEYWORDS):
            return r.user_list
    # Fallback: return the largest list (likely subscribers if channel just linked)
    biggest = max(rows, key=lambda r: r.user_list.size_for_display)
    if biggest.user_list.size_for_display > 100_000:
        return biggest.user_list
    return None


def attach_list_to_audience(client, user_list_id):
    """Update the audience to include the YouTube subscriber user_list."""
    aud_service = client.get_service("AudienceService")
    op = client.get_type("AudienceOperation")
    aud = op.update
    aud.resource_name = AUDIENCE_RESOURCE
    aud.name = "MB Belgium Concert (YouTube subscribers)"
    aud.description = "Musical Basics YouTube subscribers — primary warm audience"

    dim = audiences_pb.AudienceDimension()

    # YouTube subscriber user list segment
    seg_yt = audiences_pb.AudienceSegment()
    seg_yt.user_list.user_list = f"customers/{CID}/userLists/{user_list_id}"
    dim.audience_segments.segments.append(seg_yt)

    # Keep custom intent as supplemental signal
    seg_ci = audiences_pb.AudienceSegment()
    seg_ci.custom_audience.custom_audience = CUSTOM_AUDIENCE_RESOURCE
    dim.audience_segments.segments.append(seg_ci)

    aud.dimensions.append(dim)
    mask = field_mask_pb2.FieldMask(paths=["name", "description", "dimensions"])
    op.update_mask.CopyFrom(mask)

    resp = aud_service.mutate_audiences(customer_id=CID, operations=[op])
    return resp.results[0].resource_name


def main():
    print("=" * 60)
    print("YouTube Subscriber List Auto-Attach")
    print(f"Account: {CID} | Ad group: {AG_ID}")
    print(f"Polling every {POLL_INTERVAL_SECONDS // 60} minutes...")
    print("=" * 60)
    print()

    client = google_ads_client.get_client()
    ga_service = client.get_service("GoogleAdsService")

    attempt = 0
    while True:
        attempt += 1
        now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        print(f"[{now}] Check #{attempt} — scanning for YouTube subscriber list...")

        user_list = find_subscriber_list(client, ga_service)

        if user_list:
            print(f"  ✓ Found: \"{user_list.name}\" (id={user_list.id}, size={user_list.size_for_display})")
            print(f"  Attaching to audience {AUDIENCE_ID}...")
            try:
                result = attach_list_to_audience(client, user_list.id)
                print(f"  ✓ Audience updated: {result}")
                print()
                print("✅ Done! Subscriber list is now attached.")
                print(f"   Campaign will now target Musical Basics YouTube subscribers.")
                print(f"   User list: customers/{CID}/userLists/{user_list.id}")
                print()
                # Also update .env.local with the audience subscriber ID
                print(f"Add to .env.local:")
                print(f"  AUDIENCE_SUBSCRIBERS_ID={user_list.id}")
                sys.exit(0)
            except Exception as e:
                print(f"  ✗ Failed to attach: {e}")
                sys.exit(1)
        else:
            all_lists = list(ga_service.search(
                customer_id=CID,
                query="SELECT user_list.id, user_list.name FROM user_list"
            ))
            print(f"  No subscriber list yet (total user lists in account: {len(all_lists)})")
            print(f"  Waiting {POLL_INTERVAL_SECONDS // 60} min before next check...")
            print()
            time.sleep(POLL_INTERVAL_SECONDS)


if __name__ == "__main__":
    main()
